defmodule ElixirGpuiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :elixir_gpui

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_elixir_gpui_key",
    signing_salt: "zs8VQuNj",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug :put_cross_origin_isolation_headers

  plug Plug.Static,
    at: "/",
    from: :elixir_gpui,
    gzip: not code_reloading?,
    only: ElixirGpuiWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ElixirGpuiWeb.Router

  defp put_cross_origin_isolation_headers(conn, _opts) do
    conn
    |> Plug.Conn.put_resp_header("cross-origin-opener-policy", "same-origin")
    |> Plug.Conn.put_resp_header("cross-origin-embedder-policy", "require-corp")
    |> Plug.Conn.put_resp_header("cross-origin-resource-policy", "same-origin")
  end
end
